[db]
host = "localhost"   # env DB_HOST
port = 3306          # env DB_PORT
database = ""        # env DB_DATABASE
username = ""        # env DB_USERNAME
password = ""        # env DB_PASSWORD
log_queries = false

[logger]
level = "DEBUG"
file = "./logs/flare-indexer.log"
console = false

[metrics]
prometheus_address = "localhost:2112"

[chain]
node_url = "indexing node address"  # env CHAIN_NODE_URL
address_hrp = "flare"
chain_id = 14
eth_rpc_url = "https://flare-api.flare.network/ext/C/rpc"  # env ETH_RPC_URL
api_key = ""  # from env API_KEY
private_key_file = "path/to/private_key_file"  # env PRIVATE_KEY_FILE

[x_chain_indexer]
enabled = false

[p_chain_indexer]
enabled = true
timeout_millis = "1000ms"
start_index = 0
batch_size = 100

[uptime_cronjob]
enabled = true
timeout = "30s"
enable_voting = true
start = 1658430000
period = "302400s"
first = 123
uptime_threshold = 0.8
delete_old_uptimes_epoch_threshold = 5

[voting_cronjob]
enabled = true
timeout = "10s"
first = 211500
delay = "10s"

[contract_addresses]
voting = "0x12b3079D5b65a17EFD1665d9731FB0Adb46F14e4"  # env VOTING_CONTRACT_ADDRESS
