[db]
host = "localhost"   # from env DB_HOST
port = 3306          # from env DB_PORT
database = "flare_indexer"      # from env DB_DATABASE
username = "flareindexeruser"   # from env DB_USERNAME
password = ""                   # from env DB_PASSWORD
log_queries = false

[logger]
level = "DEBUG"
file = "./logs/flare-indexer.log"
console = false

[metrics]
prometheus_address = "localhost:2113"  # from env PROMETHEUS_ADDRESS

[chain]
node_url = "https://coston2-api-tracer.flare.network"  # from env CHAIN_NODE_URL
address_hrp = "costwo"
chain_id = 114
api_key = ""  # from env API_KEY
eth_rpc_url = "https://coston2-api.flare.network/ext/C/rpc"  # from env ETH_RPC_URL
private_key_file = "./private_key.txt"  # from env PRIVATE_KEY_FILE

[x_chain_indexer]
enabled = false

[p_chain_indexer]
enabled = false

[uptime_cronjob]
enabled = false
enable_voting = false

[voting_cronjob]
enabled = false

[mirroring_cronjob]
enabled = true
timeout = "10s"
delay = "10s"
batch_size = -1
first = 177124

[contract_addresses]
voting = "0x694905ca5f9F6c49f4748E8193B3e8053FA9E7E4"  # from env VOTING_CONTRACT_ADDRESS
mirroring = "0x3F65F2e9e25EdA1189c3aF3D596f1c2E71ececa9"  # from env MIRRORING_CONTRACT_ADDRESS



