[db]
host = "localhost"   # env DB_HOST
port = 3306          # env DB_PORT
database = ""        # env DB_DATABASE
username = ""        # env DB_USERNAME
password = ""        # env DB_PASSWORD
log_queries = false

[logger]
level = "DEBUG"
file = "./logs/flare-indexer.log"
console = false

[metrics]
prometheus_address = "localhost:2113" # from env PROMETHEUS_ADDRESS

[chain]
node_url = "indexing node address"  # env CHAIN_NODE_URL
address_hrp = "flare"
chain_id = 14
eth_rpc_url = "(indexing) node address/ext/C/rpc"  # env ETH_RPC_URL
api_key = ""  # from env API_KEY
private_key_file = "./private_key.txt"  # env PRIVATE_KEY_FILE

[x_chain_indexer]
enabled = false

[p_chain_indexer]
enabled = false

[uptime_cronjob]
enabled = false
enable_voting = false

[voting_cronjob]
enabled = false

[mirroring_cronjob]
enabled = true
timeout = "10s"
delay = "10s"
batch_size = -1
first = 211500

[contract_addresses]
voting = "0x12b3079D5b65a17EFD1665d9731FB0Adb46F14e4"  # env VOTING_CONTRACT_ADDRESS
mirroring = "0x7b61F9F27153a4F2F57Dc30bF08A8eb0cCB96C22"  # env MIRRORING_CONTRACT_ADDRESS

