version: "3.8"

services:
  flare-indexer:
    build:
      dockerfile: Dockerfile
      target: execution
      args:
        deployment: "costwo"  # or "flare"
        type: "voting"        # or "mirroring"
    volumes:
      - ../credentials/coston-voter-private-key.txt:/app/private_key.txt
      - ./logs/:/app/logs/
    environment:
      DB_HOST: "host.docker.internal"
      DB_PORT: "3306"
      DB_DATABASE: "flare_indexer_costwo"
      DB_USERNAME: "indexeruser"
      DB_PASSWORD: ""
      CHAIN_NODE_URL: "http://address:port"
      ETH_RPC_URL: "http://address:port/ext/C/rpc"
      API_KEY: ""
