version: '3.8'

volumes:
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - ./grafana-provisioning:/etc/grafana/provisioning
      - ./grafana-config.ini:/etc/grafana/grafana.ini
      - ./grafana-dashboards:/etc/dashboards
    ports:
      - "3000:3000"
